# fly.toml app configuration file generated for man-vs-talmo-api on 2023-12-06T16:58:19+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "man-vs-talmo-api"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
